### DISCUSSION TITLE
Feature request: Setting default lucide icon stroke width

### DISCUSSION THREAD

**Discussion by hackily** [tamagui/tamagui#2186] [General]
### Current Behavior

I have to manually override the lucide icon stroke width per icon. The strokewidth is currently hardcoded to 2.

### Expected Behavior

Set a default stroke width, perhaps via theme config.

### Tamagui Version

```markdown
1.88.16
```

### Platform (Web, iOS, Android)

```markdown
All platforms
```

### Reproduction

```markdown
import React from 'react';
import {X} from "@tamagui/lucide-icons";
import {YStack} from "tamagui";


const App = () => {
  return (<YStack>
    <X/>
  </YStack>);
}
```
```


### System Info

_No response_

**Comment by y4aniv** [comment]
[https://lucide.dev/guide/advanced/global-styling](https://lucide.dev/guide/advanced/global-styling)

**Comment by liamfd** [comment]
I found that just following https://lucide.dev/guide/advanced/global-styling didn't work the way I wanted it to - the style set on `.lucide` overrode the `strokeWidth` prop when instantiating icons. I didn't want to set it globally, I just wanted to update the default.

For those using tailwind, the workaround I found was to specify the default in the `@base` layer:

```css
@layer base {
   /* put in @base so tw util classes can override */
   /* https://lucide.dev/guide/advanced/global-styling */
  .lucide {
    stroke-width: 1.5;
  }
}
```

And then style the stroke width with the tailwind [`stroke-`](https://tailwindcss.com/docs/stroke-width) classes instead of using the prop, e.g.

```tsx
<Bell className="stroke-1" />
<Bell className="size-4 stroke-1" /> // with other tw styling instead of props
```
