### ISSUE TITLE
enable react-native-vector-icons with @tamagui/next-plugin

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#189]
**Is your feature request related to a problem? Please describe.**
Its difficult to get the right setup of react-native-vector-icons in combination with `withTamagui`. 

**Describe the solution you'd like**
Currently feather icons work out of the box. It would be great to extend this to react-native-vector-icons. the tamagui-starter works with expo but the NextJS compiler does not configure the loader or the loader interfers with loaders from the own config.

**Comment by dohomi** [comment]
I followed the expo documentation and the icons work until I enable `withTamagui`. After that following error occurs:
```
'No loader is configured for ".ttf" files: ../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf'

```

**Comment by dohomi** [comment]
@natew I couldn't get it work, it seems that as soon `withTamagui` next plugin is activated further configuration is not been applied. I tried several options like `disableFontSupport` without success. It seems that next build crashes before the custom webpack config is applied.

**Comment by isuhar** [comment]
Some error after upgrade tamagui from 1.0.1-beta.134 to 1.0.1-beta.191

**Comment by izakfilmalter** [comment]
Would love some input on how to resolve this.

**Comment by izakfilmalter** [comment]
I was able to get `@expo/vector-icons` working by doing the following:

1. Make a css file for the font:
    ```css
	@font-face {
	  font-family: 'material-community';
	  font-weight: normal;
	  font-style: normal;
	  src: url("../../../../../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf");
	}
	```
2. Import that css file into `_app.tsx`.
3. Use the icon as you would, `import { MaterialCommunityIcons } from '@expo/vector-icons'`.

Notes:
1. You need to figure out what the font family is of the icon set you are importing, then make adjustments to the above code. This is specifically for MaterialCommunityIcons.
2. This only started working for me with [v1.0.1-rc.3.1](https://github.com/tamagui/tamagui/releases/tag/v1.0.1-rc.3.1). On [v1.0.1-rc.2](https://github.com/tamagui/tamagui/releases/tag/v1.0.1-rc.2), nothing works.
